// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: video/video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排序方式
type SortBy int32

const (
	SortBy_SORT_BY_UNSPECIFIED SortBy = 0
	SortBy_SORT_BY_LATEST      SortBy = 1 // 最新上传
	SortBy_SORT_BY_POPULAR     SortBy = 2 // 最热（播放量）
	SortBy_SORT_BY_RATING      SortBy = 3 // 最高评分
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_UNSPECIFIED",
		1: "SORT_BY_LATEST",
		2: "SORT_BY_POPULAR",
		3: "SORT_BY_RATING",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_UNSPECIFIED": 0,
		"SORT_BY_LATEST":      1,
		"SORT_BY_POPULAR":     2,
		"SORT_BY_RATING":      3,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_proto_enumTypes[0].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_video_video_proto_enumTypes[0]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{0}
}

type SeriesEpisodesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      uint64                 `protobuf:"varint,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesEpisodesReq) Reset() {
	*x = SeriesEpisodesReq{}
	mi := &file_video_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesEpisodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesEpisodesReq) ProtoMessage() {}

func (x *SeriesEpisodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesEpisodesReq.ProtoReflect.Descriptor instead.
func (*SeriesEpisodesReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{0}
}

func (x *SeriesEpisodesReq) GetSeriesId() uint64 {
	if x != nil {
		return x.SeriesId
	}
	return 0
}

type SeriesEpisodesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episodes      []*VideoInfo           `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesEpisodesResp) Reset() {
	*x = SeriesEpisodesResp{}
	mi := &file_video_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesEpisodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesEpisodesResp) ProtoMessage() {}

func (x *SeriesEpisodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesEpisodesResp.ProtoReflect.Descriptor instead.
func (*SeriesEpisodesResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{1}
}

func (x *SeriesEpisodesResp) GetEpisodes() []*VideoInfo {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                            // 标题
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                // 简介
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`                      // 分类: 电影/电视剧/动漫/纪录片/综艺
	PosterUrl     string                 `protobuf:"bytes,5,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`   // 封面图 URL（通过 /upload 上传后存库）
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`      // 视频文件 URL
	Duration      int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`                     // 时长（秒），前端自己格式化成 "2h 13m"
	Tags          string                 `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`                              // 标签，逗号分隔 "科幻,冒险,史诗"
	Year          int32                  `protobuf:"varint,9,opt,name=year,proto3" json:"year,omitempty"`                             // 年份
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`                       // 评分 0-10
	PlayCount     int64                  `protobuf:"varint,11,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"` // 播放次数
	LikeCount     int64                  `protobuf:"varint,12,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 点赞数
	UserId        uint64                 `protobuf:"varint,13,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 上传者 ID
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // 上传时间
	SeriesId      uint64                 `protobuf:"varint,15,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Episode       int32                  `protobuf:"varint,16,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VideoInfo) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *VideoInfo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *VideoInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *VideoInfo) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *VideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *VideoInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoInfo) GetSeriesId() uint64 {
	if x != nil {
		return x.SeriesId
	}
	return 0
}

func (x *VideoInfo) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

type LikeVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Liked         bool                   `protobuf:"varint,4,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoReq) Reset() {
	*x = LikeVideoReq{}
	mi := &file_video_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoReq) ProtoMessage() {}

func (x *LikeVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoReq.ProtoReflect.Descriptor instead.
func (*LikeVideoReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{3}
}

func (x *LikeVideoReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeVideoReq) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeVideoReq) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResp) Reset() {
	*x = LikeVideoResp{}
	mi := &file_video_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResp) ProtoMessage() {}

func (x *LikeVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResp.ProtoReflect.Descriptor instead.
func (*LikeVideoResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{4}
}

func (x *LikeVideoResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *LikeVideoResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type CreateVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,4,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	Year          int32                  `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	UserId        int32                  `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoReq) Reset() {
	*x = CreateVideoReq{}
	mi := &file_video_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoReq) ProtoMessage() {}

func (x *CreateVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoReq.ProtoReflect.Descriptor instead.
func (*CreateVideoReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVideoReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateVideoReq) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CreateVideoReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateVideoReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateVideoReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CreateVideoReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateVideoReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoInfo             `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoResp) Reset() {
	*x = CreateVideoResp{}
	mi := &file_video_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResp) ProtoMessage() {}

func (x *CreateVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResp.ProtoReflect.Descriptor instead.
func (*CreateVideoResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

type UploadVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,4,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Year          int32                  `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	SeriesId      int32                  `protobuf:"varint,9,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Episode       int32                  `protobuf:"varint,10,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoReq) Reset() {
	*x = UploadVideoReq{}
	mi := &file_video_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoReq) ProtoMessage() {}

func (x *UploadVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoReq.ProtoReflect.Descriptor instead.
func (*UploadVideoReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{7}
}

func (x *UploadVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadVideoReq) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *UploadVideoReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UploadVideoReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UploadVideoReq) GetSeriesId() int32 {
	if x != nil {
		return x.SeriesId
	}
	return 0
}

func (x *UploadVideoReq) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

type UploadVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoInfo             `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResp) Reset() {
	*x = UploadVideoResp{}
	mi := &file_video_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResp) ProtoMessage() {}

func (x *UploadVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResp.ProtoReflect.Descriptor instead.
func (*UploadVideoResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{8}
}

func (x *UploadVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoReq) Reset() {
	*x = GetVideoReq{}
	mi := &file_video_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReq) ProtoMessage() {}

func (x *GetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReq.ProtoReflect.Descriptor instead.
func (*GetVideoReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetVideoReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetVideoReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoInfo             `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResp) Reset() {
	*x = GetVideoResp{}
	mi := &file_video_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResp) ProtoMessage() {}

func (x *GetVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResp.ProtoReflect.Descriptor instead.
func (*GetVideoResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *GetVideoResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type ListVideoReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Category string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// 排序方式
	SortBy SortBy `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=video.SortBy" json:"sort_by,omitempty"`
	// 分页
	Offset        int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId        uint64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tag           string `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoReq) Reset() {
	*x = ListVideoReq{}
	mi := &file_video_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoReq) ProtoMessage() {}

func (x *ListVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoReq.ProtoReflect.Descriptor instead.
func (*ListVideoReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{11}
}

func (x *ListVideoReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListVideoReq) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_SORT_BY_UNSPECIFIED
}

func (x *ListVideoReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListVideoReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVideoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListVideoReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoResp) Reset() {
	*x = ListVideoResp{}
	mi := &file_video_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoResp) ProtoMessage() {}

func (x *ListVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoResp.ProtoReflect.Descriptor instead.
func (*ListVideoResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{12}
}

func (x *ListVideoResp) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideoResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchVideosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosReq) Reset() {
	*x = SearchVideosReq{}
	mi := &file_video_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosReq) ProtoMessage() {}

func (x *SearchVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosReq.ProtoReflect.Descriptor instead.
func (*SearchVideosReq) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{13}
}

func (x *SearchVideosReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchVideosReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchVideosReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchVideosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosResp) Reset() {
	*x = SearchVideosResp{}
	mi := &file_video_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosResp) ProtoMessage() {}

func (x *SearchVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosResp.ProtoReflect.Descriptor instead.
func (*SearchVideosResp) Descriptor() ([]byte, []int) {
	return file_video_video_proto_rawDescGZIP(), []int{14}
}

func (x *SearchVideosResp) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchVideosResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_video_video_proto protoreflect.FileDescriptor

const file_video_video_proto_rawDesc = "" +
	"\n" +
	"\x11video/video.proto\x12\x05video\"0\n" +
	"\x11SeriesEpisodesReq\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\x04R\bseriesId\"B\n" +
	"\x12SeriesEpisodesResp\x12,\n" +
	"\bepisodes\x18\x01 \x03(\v2\x10.video.VideoInfoR\bepisodes\"\xb4\x03\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x05 \x01(\tR\tposterUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12\x12\n" +
	"\x04tags\x18\b \x01(\tR\x04tags\x12\x12\n" +
	"\x04year\x18\t \x01(\x05R\x04year\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01R\x06rating\x12\x1d\n" +
	"\n" +
	"play_count\x18\v \x01(\x03R\tplayCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\f \x01(\x03R\tlikeCount\x12\x17\n" +
	"\auser_id\x18\r \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tseries_id\x18\x0f \x01(\x04R\bseriesId\x12\x18\n" +
	"\aepisode\x18\x10 \x01(\x05R\aepisode\"p\n" +
	"\fLikeVideoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x04R\tcommentId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05liked\x18\x04 \x01(\bR\x05liked\"I\n" +
	"\rLikeVideoResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\"\xfd\x01\n" +
	"\x0eCreateVideoReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x04 \x01(\tR\tposterUrl\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\x12\x12\n" +
	"\x04year\x18\b \x01(\x05R\x04year\x12\x17\n" +
	"\auser_id\x18\t \x01(\x05R\x06userId\"9\n" +
	"\x0fCreateVideoResp\x12&\n" +
	"\x05video\x18\x01 \x01(\v2\x10.video.VideoInfoR\x05video\"\xc9\x01\n" +
	"\x0eUploadVideoReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x04 \x01(\tR\tposterUrl\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x12\n" +
	"\x04year\x18\b \x01(\x05R\x04year\x12\x1b\n" +
	"\tseries_id\x18\t \x01(\x05R\bseriesId\x12\x18\n" +
	"\aepisode\x18\n" +
	" \x01(\x05R\aepisode\"9\n" +
	"\x0fUploadVideoResp\x12&\n" +
	"\x05video\x18\x01 \x01(\v2\x10.video.VideoInfoR\x05video\"/\n" +
	"\vGetVideoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"Q\n" +
	"\fGetVideoResp\x12&\n" +
	"\x05video\x18\x01 \x01(\v2\x10.video.VideoInfoR\x05video\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\"\xab\x01\n" +
	"\fListVideoReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12&\n" +
	"\asort_by\x18\x02 \x01(\x0e2\r.video.SortByR\x06sortBy\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\tR\x03tag\"O\n" +
	"\rListVideoResp\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\x0fSearchVideosReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"R\n" +
	"\x10SearchVideosResp\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*^\n" +
	"\x06SortBy\x12\x17\n" +
	"\x13SORT_BY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_BY_LATEST\x10\x01\x12\x13\n" +
	"\x0fSORT_BY_POPULAR\x10\x02\x12\x12\n" +
	"\x0eSORT_BY_RATING\x10\x032\xba\x03\n" +
	"\fVideoService\x12<\n" +
	"\vCreateVideo\x12\x15.video.CreateVideoReq\x1a\x16.video.CreateVideoResp\x123\n" +
	"\bGetVideo\x12\x12.video.GetVideoReq\x1a\x13.video.GetVideoResp\x126\n" +
	"\tListVideo\x12\x13.video.ListVideoReq\x1a\x14.video.ListVideoResp\x12>\n" +
	"\vSearchVideo\x12\x16.video.SearchVideosReq\x1a\x17.video.SearchVideosResp\x126\n" +
	"\tLikeVideo\x12\x13.video.LikeVideoReq\x1a\x14.video.LikeVideoResp\x12I\n" +
	"\x12ListSeriesEpisodes\x12\x18.video.SeriesEpisodesReq\x1a\x19.video.SeriesEpisodesResp\x12<\n" +
	"\vUploadVideo\x12\x15.video.UploadVideoReq\x1a\x16.video.UploadVideoRespB\x17Z\x15ourvideos/proto/videob\x06proto3"

var (
	file_video_video_proto_rawDescOnce sync.Once
	file_video_video_proto_rawDescData []byte
)

func file_video_video_proto_rawDescGZIP() []byte {
	file_video_video_proto_rawDescOnce.Do(func() {
		file_video_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_video_proto_rawDesc), len(file_video_video_proto_rawDesc)))
	})
	return file_video_video_proto_rawDescData
}

var file_video_video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_video_video_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_video_video_proto_goTypes = []any{
	(SortBy)(0),                // 0: video.SortBy
	(*SeriesEpisodesReq)(nil),  // 1: video.SeriesEpisodesReq
	(*SeriesEpisodesResp)(nil), // 2: video.SeriesEpisodesResp
	(*VideoInfo)(nil),          // 3: video.VideoInfo
	(*LikeVideoReq)(nil),       // 4: video.LikeVideoReq
	(*LikeVideoResp)(nil),      // 5: video.LikeVideoResp
	(*CreateVideoReq)(nil),     // 6: video.CreateVideoReq
	(*CreateVideoResp)(nil),    // 7: video.CreateVideoResp
	(*UploadVideoReq)(nil),     // 8: video.UploadVideoReq
	(*UploadVideoResp)(nil),    // 9: video.UploadVideoResp
	(*GetVideoReq)(nil),        // 10: video.GetVideoReq
	(*GetVideoResp)(nil),       // 11: video.GetVideoResp
	(*ListVideoReq)(nil),       // 12: video.ListVideoReq
	(*ListVideoResp)(nil),      // 13: video.ListVideoResp
	(*SearchVideosReq)(nil),    // 14: video.SearchVideosReq
	(*SearchVideosResp)(nil),   // 15: video.SearchVideosResp
}
var file_video_video_proto_depIdxs = []int32{
	3,  // 0: video.SeriesEpisodesResp.episodes:type_name -> video.VideoInfo
	3,  // 1: video.CreateVideoResp.video:type_name -> video.VideoInfo
	3,  // 2: video.UploadVideoResp.video:type_name -> video.VideoInfo
	3,  // 3: video.GetVideoResp.video:type_name -> video.VideoInfo
	0,  // 4: video.ListVideoReq.sort_by:type_name -> video.SortBy
	3,  // 5: video.ListVideoResp.videos:type_name -> video.VideoInfo
	3,  // 6: video.SearchVideosResp.videos:type_name -> video.VideoInfo
	6,  // 7: video.VideoService.CreateVideo:input_type -> video.CreateVideoReq
	10, // 8: video.VideoService.GetVideo:input_type -> video.GetVideoReq
	12, // 9: video.VideoService.ListVideo:input_type -> video.ListVideoReq
	14, // 10: video.VideoService.SearchVideo:input_type -> video.SearchVideosReq
	4,  // 11: video.VideoService.LikeVideo:input_type -> video.LikeVideoReq
	1,  // 12: video.VideoService.ListSeriesEpisodes:input_type -> video.SeriesEpisodesReq
	8,  // 13: video.VideoService.UploadVideo:input_type -> video.UploadVideoReq
	7,  // 14: video.VideoService.CreateVideo:output_type -> video.CreateVideoResp
	11, // 15: video.VideoService.GetVideo:output_type -> video.GetVideoResp
	13, // 16: video.VideoService.ListVideo:output_type -> video.ListVideoResp
	15, // 17: video.VideoService.SearchVideo:output_type -> video.SearchVideosResp
	5,  // 18: video.VideoService.LikeVideo:output_type -> video.LikeVideoResp
	2,  // 19: video.VideoService.ListSeriesEpisodes:output_type -> video.SeriesEpisodesResp
	9,  // 20: video.VideoService.UploadVideo:output_type -> video.UploadVideoResp
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_video_video_proto_init() }
func file_video_video_proto_init() {
	if File_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_video_proto_rawDesc), len(file_video_video_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_video_proto_goTypes,
		DependencyIndexes: file_video_video_proto_depIdxs,
		EnumInfos:         file_video_video_proto_enumTypes,
		MessageInfos:      file_video_video_proto_msgTypes,
	}.Build()
	File_video_video_proto = out.File
	file_video_video_proto_goTypes = nil
	file_video_video_proto_depIdxs = nil
}
