// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: comment/comment.proto

package comment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	CreateAt      string                 `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LikeCount     int64                  `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,9,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Comment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Comment) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type ListCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReq) Reset() {
	*x = ListCommentsReq{}
	mi := &file_comment_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReq) ProtoMessage() {}

func (x *ListCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReq.ProtoReflect.Descriptor instead.
func (*ListCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ListCommentsReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ListCommentsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCommentsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommentsReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       []*Comment             `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResp) Reset() {
	*x = ListCommentsResp{}
	mi := &file_comment_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResp) ProtoMessage() {}

func (x *ListCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResp.ProtoReflect.Descriptor instead.
func (*ListCommentsResp) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{2}
}

func (x *ListCommentsResp) GetComment() []*Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ListCommentsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentsReq) Reset() {
	*x = AddCommentsReq{}
	mi := &file_comment_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentsReq) ProtoMessage() {}

func (x *AddCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentsReq.ProtoReflect.Descriptor instead.
func (*AddCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{3}
}

func (x *AddCommentsReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddCommentsReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *AddCommentsReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCommentsReq) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *AddCommentsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddCommentsReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AddCommentsReq) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type AddCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentsResp) Reset() {
	*x = AddCommentsResp{}
	mi := &file_comment_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentsResp) ProtoMessage() {}

func (x *AddCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentsResp.ProtoReflect.Descriptor instead.
func (*AddCommentsResp) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{4}
}

func (x *AddCommentsResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type LikeVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Liked         bool                   `protobuf:"varint,4,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoReq) Reset() {
	*x = LikeVideoReq{}
	mi := &file_comment_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoReq) ProtoMessage() {}

func (x *LikeVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoReq.ProtoReflect.Descriptor instead.
func (*LikeVideoReq) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{5}
}

func (x *LikeVideoReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeVideoReq) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeVideoReq) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResp) Reset() {
	*x = LikeVideoResp{}
	mi := &file_comment_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResp) ProtoMessage() {}

func (x *LikeVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResp.ProtoReflect.Descriptor instead.
func (*LikeVideoResp) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{6}
}

func (x *LikeVideoResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type LikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Liked         bool                   `protobuf:"varint,4,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	mi := &file_comment_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{7}
}

func (x *LikeCommentReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeCommentReq) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeCommentReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeCommentReq) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResp) Reset() {
	*x = LikeCommentResp{}
	mi := &file_comment_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResp) ProtoMessage() {}

func (x *LikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResp.ProtoReflect.Descriptor instead.
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{8}
}

func (x *LikeCommentResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type UpdateAvatarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarReq) Reset() {
	*x = UpdateAvatarReq{}
	mi := &file_comment_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarReq) ProtoMessage() {}

func (x *UpdateAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarReq.ProtoReflect.Descriptor instead.
func (*UpdateAvatarReq) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAvatarReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateAvatarReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateAvatarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int64                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarResp) Reset() {
	*x = UpdateAvatarResp{}
	mi := &file_comment_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarResp) ProtoMessage() {}

func (x *UpdateAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarResp.ProtoReflect.Descriptor instead.
func (*UpdateAvatarResp) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAvatarResp) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

var File_comment_comment_proto protoreflect.FileDescriptor

const file_comment_comment_proto_rawDesc = "" +
	"\n" +
	"\x15comment/comment.proto\x12\acomment\"\xeb\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x04R\x03uid\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1b\n" +
	"\tcreate_at\x18\x05 \x01(\tR\bcreateAt\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\x03R\tlikeCount\x12\x19\n" +
	"\bis_liked\x18\t \x01(\bR\aisLiked\"n\n" +
	"\x0fListCommentsReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"T\n" +
	"\x10ListCommentsResp\x12*\n" +
	"\acomment\x18\x01 \x03(\v2\x10.comment.CommentR\acomment\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc7\x01\n" +
	"\x0eAddCommentsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tcreate_at\x18\x04 \x01(\tR\bcreateAt\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\"=\n" +
	"\x0fAddCommentsResp\x12*\n" +
	"\acomment\x18\x01 \x01(\v2\x10.comment.CommentR\acomment\"p\n" +
	"\fLikeVideoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x04R\tcommentId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05liked\x18\x04 \x01(\bR\x05liked\".\n" +
	"\rLikeVideoResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\"r\n" +
	"\x0eLikeCommentReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x04R\tcommentId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05liked\x18\x04 \x01(\bR\x05liked\"0\n" +
	"\x0fLikeCommentResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\";\n" +
	"\x0fUpdateAvatarReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"7\n" +
	"\x10UpdateAvatarResp\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected2\xe1\x02\n" +
	"\x0eCommentService\x12C\n" +
	"\fListComments\x12\x18.comment.ListCommentsReq\x1a\x19.comment.ListCommentsResp\x12@\n" +
	"\vAddComments\x12\x17.comment.AddCommentsReq\x1a\x18.comment.AddCommentsResp\x12:\n" +
	"\tLikeVideo\x12\x15.comment.LikeVideoReq\x1a\x16.comment.LikeVideoResp\x12@\n" +
	"\vLikeComment\x12\x17.comment.LikeCommentReq\x1a\x18.comment.LikeCommentResp\x12J\n" +
	"\x13UpdateCommentAvatar\x12\x18.comment.UpdateAvatarReq\x1a\x19.comment.UpdateAvatarRespB\x19Z\x17ourvideos/proto/commentb\x06proto3"

var (
	file_comment_comment_proto_rawDescOnce sync.Once
	file_comment_comment_proto_rawDescData []byte
)

func file_comment_comment_proto_rawDescGZIP() []byte {
	file_comment_comment_proto_rawDescOnce.Do(func() {
		file_comment_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)))
	})
	return file_comment_comment_proto_rawDescData
}

var file_comment_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_comment_comment_proto_goTypes = []any{
	(*Comment)(nil),          // 0: comment.Comment
	(*ListCommentsReq)(nil),  // 1: comment.ListCommentsReq
	(*ListCommentsResp)(nil), // 2: comment.ListCommentsResp
	(*AddCommentsReq)(nil),   // 3: comment.AddCommentsReq
	(*AddCommentsResp)(nil),  // 4: comment.AddCommentsResp
	(*LikeVideoReq)(nil),     // 5: comment.LikeVideoReq
	(*LikeVideoResp)(nil),    // 6: comment.LikeVideoResp
	(*LikeCommentReq)(nil),   // 7: comment.LikeCommentReq
	(*LikeCommentResp)(nil),  // 8: comment.LikeCommentResp
	(*UpdateAvatarReq)(nil),  // 9: comment.UpdateAvatarReq
	(*UpdateAvatarResp)(nil), // 10: comment.UpdateAvatarResp
}
var file_comment_comment_proto_depIdxs = []int32{
	0,  // 0: comment.ListCommentsResp.comment:type_name -> comment.Comment
	0,  // 1: comment.AddCommentsResp.comment:type_name -> comment.Comment
	1,  // 2: comment.CommentService.ListComments:input_type -> comment.ListCommentsReq
	3,  // 3: comment.CommentService.AddComments:input_type -> comment.AddCommentsReq
	5,  // 4: comment.CommentService.LikeVideo:input_type -> comment.LikeVideoReq
	7,  // 5: comment.CommentService.LikeComment:input_type -> comment.LikeCommentReq
	9,  // 6: comment.CommentService.UpdateCommentAvatar:input_type -> comment.UpdateAvatarReq
	2,  // 7: comment.CommentService.ListComments:output_type -> comment.ListCommentsResp
	4,  // 8: comment.CommentService.AddComments:output_type -> comment.AddCommentsResp
	6,  // 9: comment.CommentService.LikeVideo:output_type -> comment.LikeVideoResp
	8,  // 10: comment.CommentService.LikeComment:output_type -> comment.LikeCommentResp
	10, // 11: comment.CommentService.UpdateCommentAvatar:output_type -> comment.UpdateAvatarResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_comment_comment_proto_init() }
func file_comment_comment_proto_init() {
	if File_comment_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_comment_proto_goTypes,
		DependencyIndexes: file_comment_comment_proto_depIdxs,
		MessageInfos:      file_comment_comment_proto_msgTypes,
	}.Build()
	File_comment_comment_proto = out.File
	file_comment_comment_proto_goTypes = nil
	file_comment_comment_proto_depIdxs = nil
}
