// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: danmaku/danmaku.proto

package danmaku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Danmaku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Time          float32                `protobuf:"fixed32,6,opt,name=time,proto3" json:"time,omitempty"`
	Color         string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Mode          int32                  `protobuf:"varint,8,opt,name=mode,proto3" json:"mode,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Danmaku) Reset() {
	*x = Danmaku{}
	mi := &file_danmaku_danmaku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Danmaku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Danmaku) ProtoMessage() {}

func (x *Danmaku) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_danmaku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Danmaku.ProtoReflect.Descriptor instead.
func (*Danmaku) Descriptor() ([]byte, []int) {
	return file_danmaku_danmaku_proto_rawDescGZIP(), []int{0}
}

func (x *Danmaku) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Danmaku) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Danmaku) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Danmaku) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Danmaku) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Danmaku) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Danmaku) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Danmaku) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Danmaku) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_danmaku_danmaku_proto protoreflect.FileDescriptor

const file_danmaku_danmaku_proto_rawDesc = "" +
	"\n" +
	"\x15danmaku/danmaku.proto\x12\adanmaku\"\xd9\x01\n" +
	"\aDanmaku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x04R\x03uid\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\x06 \x01(\x02R\x04time\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x12\n" +
	"\x04mode\x18\b \x01(\x05R\x04mode\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\x19Z\x17ourvideos/proto/danmakub\x06proto3"

var (
	file_danmaku_danmaku_proto_rawDescOnce sync.Once
	file_danmaku_danmaku_proto_rawDescData []byte
)

func file_danmaku_danmaku_proto_rawDescGZIP() []byte {
	file_danmaku_danmaku_proto_rawDescOnce.Do(func() {
		file_danmaku_danmaku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_danmaku_proto_rawDesc), len(file_danmaku_danmaku_proto_rawDesc)))
	})
	return file_danmaku_danmaku_proto_rawDescData
}

var file_danmaku_danmaku_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_danmaku_danmaku_proto_goTypes = []any{
	(*Danmaku)(nil), // 0: danmaku.Danmaku
}
var file_danmaku_danmaku_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_danmaku_danmaku_proto_init() }
func file_danmaku_danmaku_proto_init() {
	if File_danmaku_danmaku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_danmaku_proto_rawDesc), len(file_danmaku_danmaku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_danmaku_danmaku_proto_goTypes,
		DependencyIndexes: file_danmaku_danmaku_proto_depIdxs,
		MessageInfos:      file_danmaku_danmaku_proto_msgTypes,
	}.Build()
	File_danmaku_danmaku_proto = out.File
	file_danmaku_danmaku_proto_goTypes = nil
	file_danmaku_danmaku_proto_depIdxs = nil
}
